services:
  api:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    expose:
      - "5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/certs:/etc/ssl/certs:ro
      - ./ssl/private:/etc/ssl/private:ro
      - ./apps/frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - api
    networks:
      - webnet

networks:
  webnet:
