version: '3.9'

services:
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    expose:
      - "80"  # Internal-only, used by nginx
    networks:
      - webnet

  api:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    expose:
      - "5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/certs:/etc/ssl/certs:ro
      - ./ssl/private:/etc/ssl/private:ro
    depends_on:
      - frontend
      - api
    networks:
      - webnet

networks:
  webnet:
