services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    expose:
      - "80"
    volumes:
      - ./ssl/certs:/etc/ssl/certs:ro
      - ./ssl/private:/etc/ssl/private:ro
    networks:
      - webnet

  api:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    expose:
      - "5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl/certs:/etc/ssl/certs:ro
      - ./ssl/private:/etc/ssl/private:ro
    depends_on:
      - frontend
      - api
    networks:
      - webnet

networks:
  webnet:
